<?php
/**
 * Created by JetBrains PhpStorm.
 * User: imilyukov
 * Date: 4/21/13
 * Time: 8:35 PM
 * To change this template use File | Settings | File Templates.
 */

$product = $this->getProduct();
$helper = $this->helper('catalog/output');

$name = $product->getName();
$sortDescription = $product->getShortDescription();

$product->load();

?>

<a href="<?php echo $this->getProductUrl()?>" title="<?php echo $this->htmlEscape($this->getProductName()) ?>" class="product-image">

    <img src="<?php echo $this->getProductThumbnail()->resize(75, 90)->setWatermarkSize('30x10'); ?>" width="75" height="90" alt="<?php echo $this->htmlEscape($this->getProductName()) ?>" />

</a>

<strong><?php echo $product->getFormatedPrice() ?></strong>

<?php echo $sortDescription ? $sortDescription : $name ?><br>

<?php echo $this->__('size: ') . $product->getAttributeText('size') ?><br>

<?php echo $this->__('colour: ') . $product->getAttributeText('color') ?><br>

<?php echo $this->__('Qty: ') . $this->getQty() ?><br>

<a href="<?php echo $this->getDeleteUrl() ?>" class="delItem"></a>