<?php
/**
 * Created by JetBrains PhpStorm.
 * User: imilyukov
 * Date: 4/21/13
 * Time: 10:35 PM
 * To change this template use File | Settings | File Templates.
 */

$attributes = $this->getAllAttributes();
?>

<?php if ( $attributes->count() ): ?>

    <div class="sortingMenu">

    <form id="sup__form_filter" method="get" action="">

    <?php foreach($attributes as $attribute): ?>

        <select name="<?php echo $attribute->getName() ?>">

            <option value=""><?php echo $attribute->getDefault() ?></option>

            <?php foreach ($attribute->getOptions() as $option): ?>

                <option<?php echo $option->getSelected() ? ' selected="selected" ' : '' ?>
                        value="<?php echo $option->getValue() ?>" label="<?php echo $option->getLabel() ?>">
                    <?php echo $option->getLabel() ?>
                </option>

            <?php endforeach; ?>

        </select>

    <?php endforeach; ?>

    </form>

    </div>

<?php endif; ?>