<div class="whiteShadow"></div>
<div class="footerBg">
    <div class="footerInner">
        <ul>
            <li class="listHeader">ABOUT US</li>
            <li><a href="">about superior</a></li>
            <li><a href="">FAQ’s</a></li>
            <li><a href="">contacts us</a></li>
        </ul>
        <ul>
            <li class="listHeader">PAYMENTS & SHIPPING</li>
            <li><a href="">payment</a></li>
            <li><a href="">shipping</a></li>
            <li><a href="">return</a></li>
        </ul>
        <ul>
            <li class="listHeader">OUR PARTNERS</li>
            <li><a href="">partner1</a></li>
            <li><a href="">partner2</a></li>
            <li><a href="">partner3</a></li>
        </ul>

        <div class="follow">
            <h5>FOLLOW US</h5>
            <p>
                <a class="facebook" href=""></a>
                <a class="twitter" href=""></a>
                <a class="youtube" href=""></a>
            </p>
            <p class="copyright">
                © superior 2013
            </p>
        </div>
    </div>
</div>