<div class="header-container">
    <div class="header">
        <?php if ($this->getIsHomePage()):?>
            <h1><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"></a></h1>
        <?php else:?>
            <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
        <?php endif?>

        <div class="login">

            <a href="<?php echo $this->getUrl('login') ?>">log in</a>  /  <a href="<?php echo $this->getUrl('registration') ?>">registration</a>

        </div>
        <div class="quick-access">

            <?php echo $this->getChildHtml('topSearch') ?>
        </div>
        <?php echo $this->getChildHtml('topContainer'); ?>
    </div>
</div>
<?php echo $this->getChildHtml('topMenu') ?>
