<?php
/**
 * Created by JetBrains PhpStorm.
 * User: imilyukov
 * Date: 4/21/13
 * Time: 8:48 PM
 * To change this template use File | Settings | File Templates.
 */ ?>

<div class="clear"></div>

<div class="hotSales">

    <ul>
        <li>
            <a href="">
                <img src="pictures/1.jpg" alt="" />
								<span class="info first"><i>NEW</i>
								the latest fashion<br/> trands</span>
                <span class="overlay"></span>
            </a>
        </li>
        <li>
            <a href="">
                <img src="pictures/5.jpg" alt="" />
								<span class="info second"><i>HOT</i>
								discover the most popular</span>
                <span class="overlay"></span>
            </a>
        </li>
        <li>
            <a href="">
                <img src="pictures/6.jpg" alt="" />
								<span class="info third"><i>SALE</i>
								up to 75% off </span>
                <span class="overlay"></span>
            </a>
        </li>
    </ul>

</div>