<nav class="mainNav">

    <ul>
        <li class="homePage"><a href="">Home</a></li>
        <li><a href="">Women</a>
            <ul>
                <li>
                    <ul>
                        <li class="sublistHeader">Shop by product</li>
                        <li><a href="">Coats & Jackets</a></li>
                        <li><a href="">Denim</a></li>
                        <li><a href="">Dresses</a></li>
                        <li><a href="">Hoodies & Sweatshirts</a></li>
                        <li><a href="">Jeans</a></li>
                        <li><a href="">Jersey Tops</a></li>
                    </ul>
                    <ul>
                        <li class="sublistHeader"></li>
                        <li><a href="">Jumpers & Cardigans</a></li>
                        <li><a href="">Lingerie & Nightwear Shoes</a></li>
                        <li><a href="">Shoes</a></li>
                        <li><a href="">Shorts</a></li>
                        <li><a href="">Skirts</a></li>
                        <li><a href="">Suits & Blasers</a></li>
                    </ul>
                    <ul>
                        <li class="sublistHeader"></li>
                        <li><a href="">Swimwear & Beachwear</a></li>
                        <li><a href="">Tops</a></li>
                        <li><a href="">Trousers & Leggins</a></li>
                    </ul>
                </li>
            </ul>
        </li>
        <li><a href="">Men</a>
            <ul>
                <li>
                    <ul>
                        <li class="sublistHeader">Shop by product</li>
                        <li><a href="">Hoodies & Sweatshirts</a></li>
                        <li><a href="">Jackets & Coats</a></li>
                        <li><a href="">Jeans</a></li>
                        <li><a href="">Jumpers & Cardigans</a></li>
                        <li><a href="">Leater Jackets</a></li>
                        <li><a href="">Polo Shirts</a></li>
                    </ul>
                    <ul>
                        <li class="sublistHeader"></li>
                        <li><a href="">Shirts</a></li>
                        <li><a href="">Shoes, Boots & Trainers</a></li>
                        <li><a href="">Shorts</a></li>
                        <li><a href="">Swimwear</a></li>
                        <li><a href="">Trousers & Chinos</a></li>
                        <li><a href="">T-Shirts & Vests</a></li>
                    </ul>
                    <ul>
                        <li class="sublistHeader"></li>
                        <li><a href="">Underwear & Socks</a></li>
                    </ul>
                </li>
            </ul>
        </li>
        <li><a href="">Accessories</a>
            <ul>
                <li>
                    <ul>
                        <li class="sublistHeader">Men</li>
                        <li><a href="">Bags</a></li>
                        <li><a href="">Belts</a></li>
                        <li><a href="">Jewellery</a></li>
                        <li><a href="">Other accessories</a></li>
                        <li><a href="">Shoes</a></li>
                        <li><a href="">Small leater goods</a></li>
                    </ul>
                    <ul>
                        <li class="sublistHeader">Women</li>
                        <li><a href="">Bags</a></li>
                        <li><a href="">Belts</a></li>
                        <li><a href="">Jewellery</a></li>
                        <li><a href="">Other accessories</a></li>
                        <li><a href="">Shoes</a></li>
                        <li><a href="">Small leater goods</a></li>
                    </ul>
                </li>
            </ul>
        </li>
        <li><a href="">Gifts</a>
            <ul>
                <li>
                    <ul>
                        <li class="sublistHeader">Shop by product</li>
                    </ul>
                    <ul>
                        <li class="sublistHeader"></li>
                    </ul>
                    <ul>
                        <li class="sublistHeader"></li>
                    </ul>
                </li>
            </ul>
        </li>
    </ul>

</nav>