<div class="cart not-empty">

    <div class="cartInner">
        <h4><a href="">SHOPPING BAG</a></h4>

        <div class="productSliderWrapper">
            <button class="prev"></button>
            <button class="next"></button>

            <div class="productSlider" style="visibility: visible; overflow: hidden; position: relative; z-index: 2; left: 0px; height: 228px;">
                <ul style="margin: 0px; padding: 0px; position: relative; list-style-type: none; z-index: 1; height: 456px; top: 0px;">
                    <li style="overflow: hidden; float: none; width: 266px; height: 90px;">
                        <img alt="" src="pictures/7.png">
                        <strong>10 €</strong>
                        T-Shirt With Scoop Neck<br>
                        size: M<br>
                        colour: green<br>
                        Qty: 1<br>
                        <a href="" class="delItem"></a>
                    </li>
                    <li style="overflow: hidden; float: none; width: 266px; height: 90px;">
                        <img alt="" src="pictures/7.png">
                        <strong>10 €</strong>
                        T-Shirt With Scoop Neck<br>
                        size: M<br>
                        colour: green<br>
                        Qty: 1<br>
                        <a href="" class="delItem"></a>
                    </li>
                    <li style="overflow: hidden; float: none; width: 266px; height: 90px;">
                        <img alt="" src="pictures/7.png">
                        <strong>10 €</strong>
                        T-Shirt With Scoop Neck<br>
                        size: M<br>
                        colour: green<br>
                        Qty: 1<br>
                        <a href="" class="delItem"></a>
                    </li>
                    <li style="overflow: hidden; float: none; width: 266px; height: 90px;">
                        <img alt="" src="pictures/7.png">
                        <strong>10 €</strong>
                        T-Shirt With Scoop Neck<br>
                        size: M<br>
                        colour: green<br>
                        Qty: 1<br>
                        <a href="" class="delItem"></a>
                    </li>
                </ul>
            </div>
        </div>
        <table>
            <tbody><tr>
                <td>Subtotal products</td>
                <td>00.00 €</td>
            </tr>
            <tr>
                <td>+ delivvery fee</td>
                <td>00.000 €</td>
            </tr>
            <tr class="total">
                <td>TOTAL</td>
                <td>00.000 €</td>
            </tr>
            </tbody></table>
        <a href="" class="viewBag">VIEW BAG</a>
        <a href="" class="payNow">PAY NOW</a>
    </div>

</div>
