<?php $recentItems = $this->getRecentItems(); ?>
<div class="cart <?php count($recentItems) ? 'not-empty' : '' ?>">

    <div class="cartInner">
        <h4><a href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('SHOPPING BAG') ?></a></h4>

        <?php if ( count($recentItems) ): ?>
        <div class="productSliderWrapper">
            <button class="prev"></button>
            <button class="next"></button>

            <div class="productSlider">
                <ul>
                    <?php foreach($recentItems as $recentItem): ?>
                    <li>

                        <?php echo $this->getItemHtml($recentItem) ?>

                    </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>

        <table>
            <tbody><tr>
                <td><?php echo $this->__('Subtotal products') ?></td>
                <td><?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?></td>
            </tr>
            <tr>
                <td><?php echo $this->__('+ delivvery fee') ?></td>
                <td>00.000 €</td>
            </tr>
            <tr class="total">
                <td><?php echo $this->__('TOTAL') ?></td>
                <td><?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?></td>
            </tr>
            </tbody>
        </table>

        <a href="<?php echo $this->getUrl('checkout/cart') ?>" class="viewBag"><?php echo $this->__('VIEW BAG') ?></a>
        <a href="<?php echo $this->getCheckoutUrl() ?>" class="payNow"><?php echo $this->__('PAY NOW') ?></a>

        <?php else: ?>

        <table>
            <tbody>
                <tr>
                    <td><?php echo $this->__('0 products(s) in your bag') ?></td>
                    <td><?php echo $this->__('€00.00') ?></td>
                </tr>
                <tr>
                    <td><?php echo $this->__('Subtotal products') ?></td>
                    <td><?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?></td>
                </tr>
            </tbody>
        </table>

        <?php endif; ?>

    </div>

</div>
