<?php ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>

    <?php echo $this->getChildHtml('head') ?>

</head>
<body>

<div class="wrapper">

<!-- header -->
<header>

    <?php echo $this->getChildHtml('header') ?>

</header>
<!-- header -->


<!-- content -->
<section class="content">

    <div class="promo">
        <ul>
            <li>

                <a href=""><img src="pictures/2.jpg" alt="" /></a>

                <h5>T-Shirt With Scoop Neck</h5>

                <p class="price">10 €</p>

            </li>
            <li>

                <a href=""><img src="pictures/3.jpg" alt="" /></a>

                <h5>Armani dress with black belt</h5>

                <p class="price">20 €</p>

            </li>
            <li>

                <a href=""><img src="pictures/4.jpg" alt="" /></a>

                <h5>Exclusive leather bag</h5>

                <p class="price">60 €</p>

            </li>
            <li>

                <a href=""><img src="pictures/3.jpg" alt="" /></a>

                <h5>Armani dress with black belt</h5>

                <p class="price">20 €</p>

            </li>
            <li>

                <a href=""><img src="pictures/2.jpg" alt="" /></a>

                <h5>T-Shirt With Scoop Neck</h5>

                <p class="price">10 €</p>

            </li>
        </ul>
    </div>

    <div class="cart">

        <div class="cartInner">
            <h4><a href="">SHOPPING BAG</a></h4>

            <table>
                <tr>
                    <td>0 products(s) in your bag</td>
                    <td>00.00 €</td>
                </tr>
                <tr>
                    <td>Subtotal products</td>
                    <td>00.000 €</td>
                </tr>
            </table>
        </div>

    </div>

    <div class="clear"></div>

    <div class="hotSales">

        <ul>
            <li>
                <a href="">
                    <img src="pictures/1.jpg" alt="" />
								<span class="info first"><i>NEW</i>
								the latest fashion<br/> trands</span>
                    <span class="overlay"></span>
                </a>
            </li>
            <li>
                <a href="">
                    <img src="pictures/5.jpg" alt="" />
								<span class="info second"><i>HOT</i>
								discover the most popular</span>
                    <span class="overlay"></span>
                </a>
            </li>
            <li>
                <a href="">
                    <img src="pictures/6.jpg" alt="" />
								<span class="info third"><i>SALE</i>
								up to 75% off </span>
                    <span class="overlay"></span>
                </a>
            </li>
        </ul>

    </div>

</section><!-- content -->


</div>


<!-- footer -->
<footer>

    <?php echo $this->getChildHtml('footer') ?>

</footer>
<!-- Footer -->

</body>
</html>